name: orca:npm:ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: npm install, build, and test
        run: |
          npm ci
          npm run lint
          npm run dist
        env:
          HUSKY_SKIP_INSTALL: 1
          CI: true
      - name: run security audit of npm packages
        run: |
          npm run audit-ci
      - name: scan for exposed aws secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd ./git-secrets
          sudo make install
          cd ../
          rm -rf git-secrets
          git secrets --register-aws
          git-secrets --scan -r
      - name:  'Release a new version of package to NPM registry'
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}