name: orca:npm:ci

on:
 push:
  branches:
   - master
  paths:
   - packages/orca-design-system/**

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@master
   - uses: actions/setup-node@master
     with:
      node-version: 12
      registry-url: https://registry.npmjs.org/
   - run: npm ci
     working-directory: ./packages/orca-design-system
   - run: npm run lint
     working-directory: ./packages/orca-design-system 
   - run: npm run test
     working-directory: ./packages/orca-design-system 
