name: orcs:npm:ci

on:
  push:
    branches:
      - master
    paths:
      - packages/orcs-design-system/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./packages/orcs-design-system
      - run: npm run lint
        working-directory: ./packages/orcs-design-system
      - run: npm run test
        working-directory: ./packages/orcs-design-system
