name: Run Percy on Storybook snapshots

#on:
#  workflow_dispatch

on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
      - "master" # includes master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: |
          npm ci
          npm run bootstrap
      - name: Percy Test
        uses: percy/storybook-action@v0.1.2
        with:
          percy-flags: "--widths=1080"
          working-directory: "./packages/orcs-design-system"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
